// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'last-status': string;
  lastStatus: string;
  'potential-problem': string;
  potentialProblem: string;
}
declare const cssExports: CssExports;
export default cssExports;
