// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  description: string;
  'last-status': string;
  lastStatus: string;
}
declare const cssExports: CssExports;
export default cssExports;
