// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  worldLayer: string;
  worldLayersContainer: string;
  world_layer: string;
  world_layers_container: string;
}
declare const cssExports: CssExports;
export default cssExports;
