// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom-info': string;
  bottomInfo: string;
  edition: string;
  'game-title': string;
  gameTitle: string;
  'maps-provider': string;
  mapsProvider: string;
  menu: string;
  'menu-row': string;
  menuRow: string;
  minec: string;
  minecraft: string;
  'product-description': string;
  'product-info': string;
  productDescription: string;
  productInfo: string;
  raft: string;
  root: string;
  splash: string;
  splashAnim: string;
}
declare const cssExports: CssExports;
export default cssExports;
